-- MySQL Script generated by MySQL Workbench
-- Wed 12 Oct 2022 06:07:58 PM +03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCTOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR` (
  `ID_Doctor` INT NULL,
  `Surname` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Middle_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Doctor`),
  CONSTRAINT `fk_DOCTOR_SPECIALITY`
    FOREIGN KEY (`ID_Doctor`)
    REFERENCES `mydb`.`SPECIALITY` (`Code_Spec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_Doctor_UNIQUE` ON `mydb`.`DOCTOR` (`ID_Doctor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATIENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATIENT` (
  `N_Card` INT NOT NULL,
  `Surname` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Middle_Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  PRIMARY KEY (`N_Card`),
  CONSTRAINT CH_Phone check(Phone like '+[1-9][1-9][1-9] [1-9][1-9] [1-9][1-9][1-9]-[1-9][1-9]-[1-9][1-9]'))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `N_Card_UNIQUE` ON `mydb`.`PATIENT` (`N_Card` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SERVICES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SERVICES` (
  `Code_Srv` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Price` FLOAT NULL,
  PRIMARY KEY (`Code_Srv`),
  CHECK(Price <= 1000.0))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Code_Srv_UNIQUE` ON `mydb`.`SERVICES` (`Code_Srv` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`SPECIALITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SPECIALITY` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SPECIALITY` (
  `Code_Spec` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  PRIMARY KEY (`Code_Spec`))
ENGINE = InnoDB;

create trigger ch_code before insert on mydb.SPECIALITY
begin
    for each ROW
        set new.Code_Spec = (SELECT max(Code_Spec) + 1 FROM mydb.SCECIALITY);
end

create trigger max_code after insert on mydb.SPECIALITY
begin
    for each row
        if (new.Code_Spec > 1755) then
            SIGNAL SQLSTATE '45000';
            SET message_text = 'too much elements';
        end if;
end

CREATE UNIQUE INDEX `Code_Spec_UNIQUE` ON `mydb`.`SPECIALITY` (`Code_Spec` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`VISIT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VISIT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VISIT` (
    `ID_Doctor` INT NOT NULL,
    `ID_Pacient` INT NOT NULL,
    `Date_Visit` DATE NULL,
    `N_Visit` INT NOT NULL,
    `SERVICES_Code_Srv` INT NOT NULL,
    PRIMARY KEY (`N_Visit` , `ID_Doctor`),
    CONSTRAINT `fk_VISIT_PATIENT1` FOREIGN KEY (`ID_Pacient`)
        REFERENCES `mydb`.`PATIENT` (`N_Card`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_VISIT_DOCTOR1` FOREIGN KEY (`ID_Doctor`)
        REFERENCES `mydb`.`DOCTOR` (`ID_Doctor`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_VISIT_SERVICES1` FOREIGN KEY (`SERVICES_Code_Srv`)
        REFERENCES `mydb`.`SERVICES` (`Code_Srv`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CHECK (DATE('01.01.2022') < Date_Visit < DATE('31.12.2022'))
)  ENGINE=INNODB;

CREATE UNIQUE INDEX `ID_Doctor_UNIQUE` ON `mydb`.`VISIT` (`ID_Doctor` ASC) VISIBLE;

CREATE UNIQUE INDEX `ID_Pacient_UNIQUE` ON `mydb`.`VISIT` (`ID_Pacient` ASC) VISIBLE;

CREATE UNIQUE INDEX `VISITcol_UNIQUE` ON `mydb`.`VISIT` (`N_Visit` ASC) VISIBLE;

CREATE INDEX `fk_VISIT_SERVICES1_idx` ON `mydb`.`VISIT` (`SERVICES_Code_Srv` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
