-- Добавление данных Специальности
insert into H_Speciality values(seq_spec.nextval, 'Терапевт');
insert into H_Speciality values(seq_spec.nextval, 'Хирург');
insert into H_Speciality values(seq_spec.nextval, 'Невролог');
insert into H_Speciality values(seq_spec.nextval, 'Офтальмолог');
insert into H_Speciality values(seq_spec.nextval, 'Травмвматолог');
insert into H_Speciality values(seq_spec.nextval, 'Дерматовенеролог');
INSERT INTO H_SPECIALITY VALUES(SEQ_spec.NEXTVAL, 'Медсестра');
INSERT INTO H_SPECIALITY VALUES(SEQ_SPEC.NEXTVAL, 'Интерн');
insert into H_Speciality values(seq_spec.nextval, 'Кардиолог');

-- Добавление данных Врачи
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Быков', 'Андрей', 'Евгеньевич', 1401);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Кисегач', 'Анастасия', 'Константиновна', 1401);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Купитман', 'Иван', 'Натанович', 1406);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Скрябина', 'Любовь', 'Михайловна', 1407);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Королева', 'Маргарита', 'Павловна', 1407);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Левин', 'Борис', 'Аркадьевич', 1404);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Черноус', 'Варвара', 'Николаевна', 1408);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Романенко', 'Глеб', 'Викторович', 1401);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Лобанов', 'Семен', 'Семенович', 1408);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Ричардс', 'Фил', NULL, 1406);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Ульянова', 'Полина', 'Сергеевна', 1408);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Корнеев', 'Максим', 'Леонидович', 1402);
INSERT INTO H_DOCTOR VALUES(SEQ_DOC.NEXTVAL, 'Калинина', 'Софья', 'Яковлевна ', 1405);

-- Добавление данных Пациенты
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_1.NEXTVAL,'Безенчук', 'Федор', 'Николаевич', 'г. Артемовск', '+375256788098');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_2.NEXTVAL,'Берлага', 'Михаил', 'Александрович','г. Южногорск', '+375331234579');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_1.NEXTVAL,'Грицацуева', 'Нина', 'Ивановна','г. Прокопьевск', '+375299089096');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_1.NEXTVAL,'Паниковский', 'Самюэль','Михайлович', 'г. Криворуков', '+375244777881');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_1.NEXTVAL,'Христофоров', 'Эрнест', 'Ричардович','г. Бердянск', '+375991456682');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_2.NEXTVAL,'Щукина', 'Элла', 'Аркадьевна','г. Урюпинск', '+375113451173');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_1.NEXTVAL,'Бендер', 'Остап', 'Ибрагимович','г. Черноморск', '+375000000000');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_1.NEXTVAL,'Балаганов', 'Александр', 'Николаевич', 'г. Черноморск', '+375444567799');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_1.NEXTVAL,'Корейко', 'Александр', 'Иванович','г. Урюпинск', '+375337777777');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_1.NEXTVAL,'Козлевич','Адам', 'Казимирович', 'г. Верхнехолмск', '+375172061544');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_2.NEXTVAL,'Растопыркин ', 'Григорий', 'Феликсович','г. Урюпинск', '+375173076553');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_2.NEXTVAL,'Рукоблудов', 'Леонид', 'Ильич', 'г. Криворуков', '+375172061544' );
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_2.NEXTVAL,'Филинов', 'Василий', 'Денисович', 'г. Артемовск', '+375552347890');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_2.NEXTVAL,'Тугодумов', 'Василий', 'Федорович', 'г. Верхнехолмск', '+375297777777');
INSERT INTO H_PATIENT VALUES(SEQ_PATIENT_2.nextval,'Заныкин', 'Андрей', 'Данилович', 'г. Артемовск', '+375172124689');

-- Добавление данных Услуги
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'Консультация', 50.00);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'Первичный осмотр', 15.30);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'Рефлексотерапия', 185.60);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'Физиолечение', 5.30);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'Курс терапевтического лечения', 47.75);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'Курс профилактического лечения', 300.00);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'Ренгеноскопия', 10.00);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'ЭКГ', 0.85);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'Компьютерная томография', 450.99);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'МРТ', 560.70);
INSERT INTO H_SERVICES VALUES(SEQ_SRV.NEXTVAL, 'Анализ крови', 0.35);

-- Добавление данных Вмзиты
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 13, 116002, TO_DATE('12.09.22','DD.MM.RR'), 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 21, 116003, TO_DATE('12.09.22','DD.MM.RR'), 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 11, 216002, TO_DATE('12.09.22','DD.MM.RR'), 150);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 20, 116006, TO_DATE('13.09.22','DD.MM.RR'), 160);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 18, 216003, TO_DATE('13.09.22','DD.MM.RR'), 120);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 11, 116007, TO_DATE('14.09.22','DD.MM.RR'), 150);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 20, 216004, TO_DATE('15.09.22','DD.MM.RR'), 160);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 14, 116008, TO_DATE('19.09.22','DD.MM.RR'), 210);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 19, 216001, TO_DATE('19.09.22','DD.MM.RR'), 170);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 21, 116003, TO_DATE('19.09.22','DD.MM.RR'), 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL,NULL,216005, TO_DATE('20.09.22','DD.MM.RR'), 170);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 18, 216002, TO_DATE('21.09.22','DD.MM.RR'), 140);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 16, 116004, TO_DATE('21.09.22','DD.MM.RR'), 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 18, NULL,   TO_DATE('22.09.22','DD.MM.RR'), 120);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL,NULL,216001, TO_DATE('23.09.22','DD.MM.RR'), 210);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 22, 216007, TO_DATE('26.09.22','DD.MM.RR'), 130);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 21, 116003, TO_DATE('26.09.22','DD.MM.RR'), 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL,NULL,216001, TO_DATE('27.09.22','DD.MM.RR'), 170);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (SEQ_VISIT.NEXTVAL, 22, 116008, TO_DATE('28.09.22','DD.MM.RR'), 130);
Insert into H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) values (SEQ_VISIT.NEXTVAL, 12, 116007, to_date('29.09.22','DD.MM.RR'), 200);