-- MySQL Script generated by MySQL Workbench
-- Sun 12 Feb 2023 10:22:03 PM +03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`application` ;

CREATE TABLE IF NOT EXISTS `mydb`.`application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_type` INT NOT NULL,
  `tenant_id` INT NOT NULL,
  `date` DATE NULL,
  `dispatcher_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tenant_id`),
  INDEX `fk_application_tenant_idx` (`tenant_id` ASC) VISIBLE,
  INDEX `fk_application_dispatcher1_idx` (`dispatcher_id` ASC) VISIBLE,
  CONSTRAINT `fk_application_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `mydb`.`tenant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_application_dispatcher1`
    FOREIGN KEY (`dispatcher_id`)
    REFERENCES `mydb`.`dispatcher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dispatcher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dispatcher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dispatcher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tenant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tenant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tenant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`worker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`worker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_type` INT NOT NULL,
  `busy` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`work_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`work_plan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`work_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ADMIN (
  ID            SERIAL PRIMARY KEY,
  NAME          VARCHAR(50) NOT NULL,
  LASTNAME      VARCHAR(50) NOT NULL
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
